[workspace]
members = ["lambda-appsync", "lambda-appsync-proc"]
resolver = "2"

[workspace.package]
version = "0.0.1"
rust-version = "1.81.0"
edition = "2021"
authors = ["Jérémie RODON <jeremie.rodon@gmail.com>"]
license = "MIT"
