name: CI

on:
  push:
    branches: [master]
    paths:
      - "lambda-appsync/**"
      - "lambda-appsync-proc/**"
      - "Cargo.toml"
      - ".github/workflows/**"
  pull_request:
    branches: [master]
    paths:
      - "lambda-appsync/**"
      - "lambda-appsync-proc/**"
      - "Cargo.toml"
      - ".github/workflows/**"

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Pin dependencies
        run: |
          # Create lockfile
          cargo update
          # Pin base64ct to 1.7.3
          cargo update -p base64ct --precise 1.7.3

      - name: Cargo Format Check
        run: cargo fmt --all -- --check

      - name: Clippy Check
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Doc Check
        run: RUSTDOCFLAGS="-D warnings" cargo doc --all-features --no-deps --document-private-items

      - name: Run Tests
        run: cargo test --all-features

      - name: Build Documentation
        run: cargo doc --no-deps --document-private-items

  msrv:
    name: MSRV Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust 1.81.0
        uses: dtolnay/rust-toolchain@1.81.0

      - name: Pin dependencies
        run: |
          # Create lockfile
          cargo update
          # Pin base64ct to 1.7.3
          cargo update -p base64ct --precise 1.7.3

      - name: Check MSRV Build
        run: cargo check --all-features
