name: CI

on:
  push:
    branches: [master]
    paths:
      - "lambda-appsync/**"
      - "lambda-appsync-proc/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/**"
  pull_request:
    branches: [master]
    paths:
      - "lambda-appsync/**"
      - "lambda-appsync-proc/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/**"

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust 1.81.0
        uses: dtolnay/rust-toolchain@1.81.0
        with:
          components: rustfmt, clippy

      - name: Cargo Format Check
        run: cargo --locked fmt --all -- --check

      - name: Clippy Check
        run: cargo --locked clippy --all-targets --all-features -- -D warnings

      - name: Doc Check
        run: RUSTDOCFLAGS="-D warnings" cargo --locked doc --all-features --no-deps --document-private-items

      - name: Run Tests
        run: cargo --locked test --all-features

      - name: Build Documentation
        run: cargo --locked doc --no-deps --document-private-items

      - name: Check MSRV Build
        run: cargo --locked check --all-features
